# configs/prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8000']

  - job_name: 'go_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['go_service:8081']

  - job_name: 'redis'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['redis:6379']
