# shellcheck disable=SC2006,SC1009,SC1073,SC1065,SC2215,SC2211,SC2046,SC2296
# docker/docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: gpt4o_finetuning_project_app
    restart: always
    environment:
      - OPENAI_API_KEY=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
      - JWT_SECRET=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TTL=
      - LOG_LEVEL_CONSOLE=
      - LOG_LEVEL_FILE=
      - LOG_LEVEL_SRC=
      - LOG_LEVEL_ROOT=
      - DATABASE_URL=
    depends_on:
      - redis
    networks:
      - app-network
    volumes:
      - ./logs:/app/logs

  go_service:
    build:
      context: src/optimizations/go_service
      dockerfile: Dockerfile
    container_name: gpt4o_finetuning_project_go_service
    restart: always
    ports:
      - "8081:8081"
    networks:
      - app-network
    volumes:
      - ./logs:/app/logs

  redis:
    image: "redis:alpine"
    container_name: gpt4o_finetuning_project_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: ["redis-server", "--appendonly", "yes"]

  nginx:
    image: "nginx:alpine"
    container_name: gpt4o_finetuning_project_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - app
      - go_service
    networks:
      - app-network

  prometheus:
    image: "prom/prometheus:latest"
    container_name: gpt4o_finetuning_project_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_alerts.yml:/etc/prometheus/prometheus_alerts.yml
    ports:
      - "9090:9090"
    networks:
      - app-network

  grafana:
    image: "grafana/grafana:latest"
    container_name: gpt4o_finetuning_project_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
